(()=>{'use strict';const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],cv=$('#cv'),cx=cv.getContext('2d'),host=$('#three');let S={tool:'rect',view:'2d',shapes:[],profiles:[],sel:[],draft:null,poly:[],lasso:null,tab:'entity',multi:false,next:1,layers:{shapes:1,lsf:1,labels:1},lsf:0},meter=70,dpr=1,scene,camera,ren,orbit,ray,ptr,trans,map=new Map(),pushTarget=null;
const gid=p=>(p||'O')+(S.next++).toString().padStart(3,'0'),name=k=>({line:'Linha',rect:'Retângulo',circle:'Círculo',arc:'Arco',polygon:'Polígono'})[k]||k,closed=s=>['rect','circle','polygon'].includes(s.kind),toast=x=>{let t=$('#toast');t.textContent=x;t.classList.remove('hide');setTimeout(()=>t.classList.add('hide'),2400)},all=()=>[...S.shapes,...S.profiles],item=id=>all().find(x=>x.id===id);
function setTool(t){S.tool=t;$$('[data-t]').forEach(b=>b.classList.toggle('on',b.dataset.t===t));$('#tool').textContent='Ferramenta: '+name(t);if(t==='orbit'&&S.view==='3d')toast('Órbita ativa: arraste para rodar 360°.')}
function resize(){let r=cv.getBoundingClientRect();dpr=Math.max(1,devicePixelRatio||1);cv.width=r.width*dpr;cv.height=r.height*dpr;cx.setTransform(dpr,0,0,dpr,0,0);draw2();resize3()}
function pxy(e){let r=cv.getBoundingClientRect();return{x:Math.round((e.clientX-r.left)/11)*11,y:Math.round((e.clientY-r.top)/11)*11}}
function bounds(s){if(s.kind==='rect')return{x:Math.min(s.a.x,s.b.x),y:Math.min(s.a.y,s.b.y),w:Math.abs(s.b.x-s.a.x),h:Math.abs(s.b.y-s.a.y)};if(s.kind==='circle')return{x:s.c.x-s.r,y:s.c.y-s.r,w:2*s.r,h:2*s.r};if(s.kind==='polygon'){let x=s.points.map(p=>p.x),y=s.points.map(p=>p.y);return{x:Math.min(...x),y:Math.min(...y),w:Math.max(...x)-Math.min(...x),h:Math.max(...y)-Math.min(...y)}}return{x:0,y:0,w:0,h:0}}
function pts(s){if(s.kind==='rect'){let b=bounds(s);return[{x:b.x,y:b.y},{x:b.x+b.w,y:b.y},{x:b.x+b.w,y:b.y+b.h},{x:b.x,y:b.y+b.h}]}if(s.kind==='circle'){let a=[];for(let i=0;i<48;i++){let q=i/48*Math.PI*2;a.push({x:s.c.x+Math.cos(q)*s.r,y:s.c.y+Math.sin(q)*s.r})}return a}return s.points||[]}
function path(s){cx.beginPath();if(s.kind==='line'){cx.moveTo(s.a.x,s.a.y);cx.lineTo(s.b.x,s.b.y)}else if(s.kind==='rect'){let b=bounds(s);cx.rect(b.x,b.y,b.w,b.h)}else if(s.kind==='circle')cx.arc(s.c.x,s.c.y,s.r,0,Math.PI*2);else if(s.kind==='polygon'){s.points.forEach((p,i)=>i?cx.lineTo(p.x,p.y):cx.moveTo(p.x,p.y));cx.closePath()}else if(s.kind==='arc')cx.arc(s.c.x,s.c.y,s.r,s.a0,s.a1)}
function drawShape(s,pre){let sel=S.sel.includes(s.id);cx.save();path(s);cx.strokeStyle=sel?'#f5a52a':pre?'#159447':'#07587a';cx.lineWidth=sel?4:3;cx.setLineDash(pre?[8,5]:[]);if(closed(s)){cx.fillStyle=sel?'#f5a52220':'#1279b710';cx.fill()}cx.stroke();cx.restore();if(S.layers.labels&&!pre){let b=bounds(s);cx.fillStyle='#075071';cx.font='bold 13px Arial';cx.fillText(s.name||name(s.kind),b.x+b.w/2+4,b.y+b.h/2-5)}}
function draw2(){if(S.view!=='2d')return;let w=cv.clientWidth,h=cv.clientHeight;cx.clearRect(0,0,w,h);cx.strokeStyle='#4ca36a88';cx.beginPath();cx.moveTo(0,h*.72);cx.lineTo(w,h*.72);cx.stroke();cx.strokeStyle='#d35c5c77';cx.beginPath();cx.moveTo(w*.16,0);cx.lineTo(w*.16,h);cx.stroke();if(S.layers.shapes)S.shapes.forEach(s=>drawShape(s));if(S.draft)drawShape(S.draft,1);if(S.poly.length){cx.save();cx.setLineDash([5,4]);cx.strokeStyle='#159447';cx.beginPath();S.poly.forEach((p,i)=>i?cx.lineTo(p.x,p.y):cx.moveTo(p.x,p.y));cx.stroke();cx.restore()}if(S.lasso){let b=box(S.lasso.a,S.lasso.b);cx.save();cx.setLineDash([6,4]);cx.strokeStyle='#159447';cx.fillStyle='#15944718';cx.strokeRect(b.x,b.y,b.w,b.h);cx.fillRect(b.x,b.y,b.w,b.h);cx.restore()}}
const box=(a,b)=>({x:Math.min(a.x,b.x),y:Math.min(a.y,b.y),w:Math.abs(a.x-b.x),h:Math.abs(a.y-b.y)});function seg(p,a,b){let dx=b.x-a.x,dy=b.y-a.y,l=dx*dx+dy*dy||1,t=Math.max(0,Math.min(1,((p.x-a.x)*dx+(p.y-a.y)*dy)/l));return Math.hypot(p.x-a.x-t*dx,p.y-a.y-t*dy)}function inp(p,a){let n=0;for(let i=0,j=a.length-1;i<a.length;j=i++)if((a[i].y>p.y)!=(a[j].y>p.y)&&p.x<(a[j].x-a[i].x)*(p.y-a[i].y)/(a[j].y-a[i].y)+a[i].x)n=!n;return n}
function hit(p){for(let i=S.shapes.length-1;i>=0;i--){let s=S.shapes[i];if(s.kind==='rect'){let b=bounds(s);if(p.x>=b.x-8&&p.x<=b.x+b.w+8&&p.y>=b.y-8&&p.y<=b.y+b.h+8)return s}if(s.kind==='circle'&&Math.hypot(p.x-s.c.x,p.y-s.c.y)<=s.r+9)return s;if(s.kind==='polygon'&&inp(p,s.points))return s;if(s.kind==='line'&&seg(p,s.a,s.b)<9)return s}return null}
function select(o,add){if(!o){if(!add)S.sel=[];$('#status').textContent='Nenhum objeto selecionado.'}else if(add||S.multi){S.sel.includes(o.id)?S.sel=S.sel.filter(x=>x!==o.id):S.sel.push(o.id);$('#status').textContent=S.sel.length+' objeto(s) selecionado(s).'}else{S.sel=[o.id];$('#status').textContent='Selecionado: '+o.name}draw2();sync();panel()}
function fix(s){s.id=gid();s.name=name(s.kind)+' '+(S.shapes.length+1);s.height=s.height||0;S.shapes.push(s);S.draft=null;draw2();panel();toast(s.name+' fixado.')}
cv.onpointerdown=e=>{let p=pxy(e);if(S.tool==='select')return select(hit(p),e.ctrlKey||e.metaKey);if(S.tool==='lasso'){S.lasso={a:p,b:p};return}if(['line','rect','circle'].includes(S.tool)){S.draft=S.tool==='circle'?{kind:'circle',c:p,r:0}:{kind:S.tool,a:p,b:p};return}if(S.tool==='polygon'){S.poly.push(p);draw2();return}if(S.tool==='arc'){S.arc=S.arc||[];S.arc.push(p);if(S.arc.length===3){let[c,a,b]=S.arc;fix({kind:'arc',c,r:Math.hypot(a.x-c.x,a.y-c.y),a0:Math.atan2(a.y-c.y,a.x-c.x),a1:Math.atan2(b.y-c.y,b.x-c.x)});S.arc=[]}}};cv.onpointermove=e=>{let p=pxy(e);$('#coords').textContent='X: '+(p.x/meter).toFixed(3)+' · Y: '+(p.y/meter).toFixed(3)+' · Z: 0.000';if(S.draft){S.draft.kind==='circle'?S.draft.r=Math.hypot(p.x-S.draft.c.x,p.y-S.draft.c.y):S.draft.b=p;draw2()}if(S.lasso){S.lasso.b=p;draw2()}};cv.onpointerup=e=>{let p=pxy(e);if(S.draft){if(S.draft.kind==='circle'){if(S.draft.r>6)fix(S.draft)}else if(Math.hypot(p.x-S.draft.a.x,p.y-S.draft.a.y)>6)fix(S.draft)}if(S.lasso){let b=box(S.lasso.a,S.lasso.b);S.sel=S.shapes.filter(s=>{let q=bounds(s);return q.x>=b.x&&q.y>=b.y&&q.x+q.w<=b.x+b.w&&q.y+q.h<=b.y+b.h}).map(s=>s.id);S.lasso=null;$('#status').textContent=S.sel.length+' objeto(s) selecionado(s) por laço.';draw2();panel()}};window.onkeydown=e=>{if(e.key==='Enter'&&S.poly.length>=3){fix({kind:'polygon',points:[...S.poly]});S.poly=[]}if(e.key==='Escape'){S.draft=null;S.poly=[];S.lasso=null;S.arc=[];draw2()}if((e.key==='Delete'||e.key==='Backspace')&&document.activeElement.tagName!=='INPUT')del()};
function init3(){if(scene)return;scene=new THREE.Scene();scene.background=new THREE.Color('#bde4f1');camera=new THREE.PerspectiveCamera(48,1,.1,500);camera.position.set(10,-13,10);ren=new THREE.WebGLRenderer({antialias:true});ren.setPixelRatio(Math.min(2,devicePixelRatio));host.appendChild(ren.domElement);scene.add(new THREE.HemisphereLight(0xf2ffff,0x668a60,2));let d=new THREE.DirectionalLight(0xffffff,2);d.position.set(8,-10,17);scene.add(d);let g=new THREE.Mesh(new THREE.PlaneGeometry(100,100),new THREE.MeshStandardMaterial({color:0xbdd8ad}));g.rotation.x=-Math.PI/2;g.position.z=-.04;scene.add(g);scene.add(new THREE.GridHelper(70,70,0x75a078,0x9ab79d));orbit=new THREE.OrbitControls(camera,ren.domElement);orbit.enableDamping=true;orbit.target.set(0,0,1.4);orbit.maxPolarAngle=Math.PI-.03;ray=new THREE.Raycaster();ptr=new THREE.Vector2();trans=new THREE.TransformControls(camera,ren.domElement);trans.addEventListener('dragging-changed',x=>orbit.enabled=!x.value);scene.add(trans);ren.domElement.onpointermove=e=>{let r=ren.domElement.getBoundingClientRect();ptr.x=(e.clientX-r.left)/r.width*2-1;ptr.y=-(e.clientY-r.top)/r.height*2+1};ren.domElement.onpointerdown=click3;resize3();(function loop(){requestAnimationFrame(loop);orbit.update();ren.render(scene,camera)})()}
function world(p){return{x:(p.x-400)/meter,y:(520-p.y)/meter}}function geo(s){let a=pts(s).map(world),sh=new THREE.Shape();a.forEach((p,i)=>i?sh.lineTo(p.x,p.y):sh.moveTo(p.x,p.y));sh.closePath();return new THREE.ExtrudeGeometry(sh,{depth:Math.max(.02,s.height||.02),bevelEnabled:false,curveSegments:24})}function build(){init3();map.forEach(o=>scene.remove(o));map.clear();if(S.layers.shapes)S.shapes.filter(closed).forEach(s=>{let m=new THREE.Mesh(geo(s),new THREE.MeshStandardMaterial({color:S.sel.includes(s.id)?0xf5a52a:0xd9eef0,roughness:.7}));m.position.z=s.elev||0;m.userData.id=s.id;scene.add(m);map.set(s.id,m)});if(S.lsf&&S.layers.lsf)S.profiles.forEach(p=>{let a=world(p.a),b=world(p.b),v=new THREE.Vector3(b.x-a.x,b.y-a.y,p.z1-p.z0),L=v.length(),m=new THREE.Mesh(new THREE.BoxGeometry(.055,.055,L),new THREE.MeshStandardMaterial({color:S.sel.includes(p.id)?0xf5a52a:0x287188,metalness:.5}));m.position.set((a.x+b.x)/2,(a.y+b.y)/2,(p.z0+p.z1)/2);m.quaternion.setFromUnitVectors(new THREE.Vector3(0,0,1),v.normalize());m.userData.id=p.id;scene.add(m);map.set(p.id,m)});fit(false);sync()}
function resize3(){if(!ren)return;let r=host.getBoundingClientRect();camera.aspect=r.width/r.height;camera.updateProjectionMatrix();ren.setSize(r.width,r.height)}function click3(e){if(e.button||S.tool==='orbit')return;ray.setFromCamera(ptr,camera);let h=ray.intersectObjects([...map.values()])[0];if(!h){if(S.tool==='select')select(null);return}let o=item(h.object.userData.id);select(o,e.ctrlKey||e.metaKey);if(S.tool==='move'){trans.setMode('translate');trans.attach(h.object)}if(S.tool==='rotate'){trans.setMode('rotate');trans.attach(h.object)}if(pushTarget&&o===pushTarget)$('#pop').classList.remove('hide')}
function sync(){map.forEach((m,i)=>m.material.color.set(S.sel.includes(i)?0xf5a52a:(item(i)?.type==='profile'?0x287188:0xd9eef0)));if(S.sel.length!==1)trans?.detach()}function fit(msg){if(!scene||!map.size)return;let b=new THREE.Box3();map.forEach(o=>b.expandByObject(o));let c=b.getCenter(new THREE.Vector3()),z=b.getSize(new THREE.Vector3()).length()||7;orbit.target.copy(c);camera.position.copy(c.clone().add(new THREE.Vector3(z,-z*1.3,z*.85)));orbit.update();msg&&toast('Vista 3D ajustada.')}
function v(x){S.view=x;cv.classList.toggle('hide',x!=='2d');host.classList.toggle('hide',x!=='3d');$('#v2').classList.toggle('on',x==='2d');$('#v3').classList.toggle('on',x==='3d');$('#badge').textContent=x==='2d'?'Vista 2D — Planta':'Vista 3D — Estrutura LSF';if(x==='3d')build();else draw2()}
function push(){let o=S.shapes.find(x=>S.sel.includes(x.id)&&closed(x));if(!o)return toast('Selecione um retângulo, círculo ou polígono fechado.');pushTarget=o;v('3d');build();$('#height').value=(o.height||2.7).toFixed(2);$('#pop').classList.remove('hide')}function apply(){if(!pushTarget)return;let h=+$('#height').value;if(!(h>.05))return toast('Indique uma altura válida.');pushTarget.height=h;$('#pop').classList.add('hide');build();toast('Volume criado com '+h.toFixed(2)+' m.')}
function lsf(){let q=S.shapes.filter(closed);if(!q.length)return toast('Desenhe primeiro uma forma fechada.');S.profiles=[];let n=1;q.forEach((s,k)=>{s.height=s.height||2.7;let z=s.elev||0,h=s.height,p='P'+String(k+1).padStart(2,'0'),a=pts(s);for(let i=0;i<a.length;i++){let x=a[i],y=a[(i+1)%a.length];S.profiles.push({id:gid('U'),type:'profile',kind:'Guia inferior',profile:'U90x40x0.95',name:p+'-U'+n++,panel:p,a:x,b:y,z0:z,z1:z});S.profiles.push({id:gid('U'),type:'profile',kind:'Guia superior',profile:'U90x40x0.95',name:p+'-U'+n++,panel:p,a:x,b:y,z0:z+h,z1:z+h});let L=Math.hypot(y.x-x.x,y.y-x.y),m=Math.max(2,Math.floor(L/(meter*.6))+1);for(let j=0;j<m;j++){let t=j/(m-1),r={x:x.x+(y.x-x.x)*t,y:x.y+(y.y-x.y)*t};S.profiles.push({id:gid('C'),type:'profile',kind:'Montante',profile:'C90x40x0.95',name:p+'-M'+n++,panel:p,a:r,b:r,z0:z,z1:z+h})}}});S.lsf=1;v('3d');build();panel();toast(S.profiles.length+' perfis individuais gerados.')}
function move(dx,dy,dz){let a=S.sel.map(item).filter(Boolean);if(!a.length)return toast('Selecione uma ou mais peças.');a.forEach(o=>{if(o.type==='profile'){o.a.x+=dx*meter;o.a.y+=dy*meter;o.b.x+=dx*meter;o.b.y+=dy*meter;o.z0+=dz;o.z1+=dz}else if(o.kind==='rect'){o.a.x+=dx*meter;o.a.y+=dy*meter;o.b.x+=dx*meter;o.b.y+=dy*meter;o.elev=(o.elev||0)+dz}else if(o.kind==='circle'){o.c.x+=dx*meter;o.c.y+=dy*meter;o.elev=(o.elev||0)+dz}else if(o.kind==='polygon'){o.points.forEach(p=>{p.x+=dx*meter;p.y+=dy*meter});o.elev=(o.elev||0)+dz}});build();draw2();panel();toast(a.length+' elemento(s) movido(s).')}
function del(){if(!S.sel.length)return toast('Selecione antes de apagar.');if(!confirm('Apagar '+S.sel.length+' elemento(s)?'))return;let q=new Set(S.sel);S.shapes=S.shapes.filter(x=>!q.has(x.id));S.profiles=S.profiles.filter(x=>!q.has(x.id));S.sel=[];build();draw2();panel()}
function csv(){let r=[['PROJETO','PAINEL','REFERENCIA','TIPO','PERFIL','COMPRIMENTO_MM','COTA_Z_MM']];if(S.profiles.length)S.profiles.forEach(p=>r.push(['Aloe LSF 360',p.panel,p.name,p.kind,p.profile,(Math.hypot(p.b.x-p.a.x,p.b.y-p.a.y,p.z1-p.z0)/meter*1000).toFixed(1),(p.z0*1000).toFixed(1)]));else S.shapes.filter(closed).forEach((s,i)=>r.push(['Aloe LSF 360','P'+(i+1),s.name,name(s.kind),s.profile||'—',((s.height||0)*1000).toFixed(1),((s.elev||0)*1000).toFixed(1)]));if(r.length===1)return toast('Sem dados para CSV.');let t=r.map(x=>x.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(';')).join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([t],{type:'text/csv'}));a.download='aloe_lsf360_fabrico.csv';a.click();URL.revokeObjectURL(a.href);toast('CSV gerado.')}
function panel(){
  const p=$('#panel'), sel=S.sel.map(item).filter(Boolean);
  if(S.tab==='entity'){
    const rows=all().map(o=>`<div class="row ${S.sel.includes(o.id)?'active':''}"><div><b>${o.name}</b><small>${o.type==='profile'?o.kind:name(o.kind)} · ${o.profile||'—'}</small></div><button data-id="${o.id}">Selecionar</button></div>`).join('')||'<p>Nenhum objeto criado.</p>';
    p.innerHTML=`<div class="card"><h3>Propriedades</h3><p>${sel.length?`<b>${sel.length} selecionado(s)</b><br>Tipo: ${sel[0].type==='profile'?sel[0].kind:name(sel[0].kind)}<br>Perfil: ${sel[0].profile||'—'}`:'Selecione um objeto no desenho ou na lista.'}</p></div><div class="card"><h3>Objetos do projeto</h3><div class="list">${rows}</div></div>`;
    $$('[data-id]').forEach(b=>b.onclick=()=>select(item(b.dataset.id),S.multi));
    return;
  }
  if(S.tab==='selection'){
    const prof=[...new Set(all().map(o=>o.profile).filter(Boolean))];
    p.innerHTML=`<div class="card"><h3>Seleção por objeto ou perfil</h3><div class="buttons"><button class="btn" id="multi">${S.multi?'Desativar':'Ativar'} múltipla</button><button class="btn" id="clear">Limpar</button></div><div class="field"><label>Tipo</label><select id="ft"><option value="all">Todos</option><option value="rect">Retângulos</option><option value="circle">Círculos</option><option value="polygon">Polígonos</option><option value="profile">Perfis LSF</option></select></div><div class="field"><label>Perfil</label><select id="fp"><option value="all">Todos</option>${prof.map(x=>`<option>${x}</option>`).join('')}</select></div><button class="btn green" id="go">Selecionar filtrados</button></div><div class="card"><h3>Mover seleção</h3><div class="field"><label>Passo</label><select id="step"><option value="0.01">10 mm</option><option value="0.05" selected>50 mm</option><option value="0.10">100 mm</option><option value="0.50">500 mm</option></select></div><div class="movegrid"><i></i><button data-m="0,0,1" class="z">↑</button><i></i><button data-m="-1,0,0">←</button><button data-m="0,1,0">◎</button><button data-m="1,0,0">→</button><i></i><button data-m="0,0,-1" class="z">↓</button><i></i></div><div class="buttons"><button class="btn danger" id="del">Apagar selecionado</button><button class="btn" id="orb">Órbita</button></div></div>`;
    $('#multi').onclick=()=>{S.multi=!S.multi;panel()};
    $('#clear').onclick=()=>select(null);
    $('#go').onclick=()=>{const t=$('#ft').value,f=$('#fp').value;S.sel=all().filter(o=>(t==='all'||(t==='profile'?o.type==='profile':o.kind===t))&&(f==='all'||o.profile===f)).map(o=>o.id);$('#status').textContent=S.sel.length+' selecionado(s) por filtro.';panel();draw2();sync()};
    $$('[data-m]').forEach(b=>b.onclick=()=>{const [x,y,z]=b.dataset.m.split(',').map(Number),q=+$('#step').value;move(x*q,y*q,z*q)});
    $('#del').onclick=del;$('#orb').onclick=()=>{setTool('orbit');v('3d')};
    return;
  }
  if(S.tab==='profiles'){
    p.innerHTML=`<div class="card"><h3>Perfis LSF</h3><p>Famílias previstas: C/U 90–300 mm, L, Ómega/Cartola, vigas e perfis de piso.</p><div class="field"><label>Perfil a aplicar</label><select id="pp"><option>C90x40x0.95</option><option>C100x40x0.95</option><option>C140x40x1.20</option><option>C200x50x1.50</option><option>U90x40x0.95</option><option>L75x75x1.20</option><option>Ómega 70x30x0.95</option></select></div><button class="btn green" id="applyP">Aplicar à seleção</button></div>`;
    $('#applyP').onclick=()=>{const q=$('#pp').value;S.sel.map(item).filter(Boolean).forEach(o=>o.profile=q);build();panel();toast('Perfil aplicado.')};
    return;
  }
  if(S.tab==='geo'){
    p.innerHTML=`<div class="card"><h3>Geolocalização</h3><p>Rua, número, código postal e localidade. A consulta de terreno por API será ligada na fase seguinte.</p><div class="field"><label>Rua e número</label><input id="street" placeholder="Rua das Acácias, 123"></div><div class="field"><label>Código postal</label><input id="post" placeholder="3080-123"></div><div class="field"><label>Localidade</label><input id="city" placeholder="Figueira da Foz"></div><button class="btn green" id="geoSave">Guardar localização</button></div>`;
    $('#geoSave').onclick=()=>toast('Localização guardada.');
    return;
  }
  p.innerHTML=`<div class="card"><h3>CSV de fabrico</h3><p>Exporta lista de corte e perfis individuais quando a estrutura LSF foi gerada.</p><button class="btn green" id="csv2">Gerar CSV de fabrico</button></div>`;
  $('#csv2').onclick=csv;
} 
$$('[data-t]').forEach(b=>b.onclick=()=>setTool(b.dataset.t));$('#push').onclick=push;$('#move').onclick=()=>{setTool('move');v('3d')};$('#rotate').onclick=()=>{setTool('rotate');v('3d')};$('#orbit').onclick=()=>{setTool('orbit');v('3d')};$('#erase').onclick=del;$('#leftMove').onclick=()=>$('#move').click();$('#leftOrbit').onclick=()=>$('#orbit').click();$('#leftErase').onclick=del;$('#lsf').onclick=lsf;$('#csv').onclick=csv;$('#fit').onclick=()=>{v('3d');fit(1)};$('#v2').onclick=()=>v('2d');$('#v3').onclick=()=>v('3d');$('#topView').onclick=()=>v(S.view==='2d'?'3d':'2d');$('#applyHeight').onclick=apply;$$('.tab').forEach(b=>b.onclick=()=>{$$('.tab').forEach(x=>x.classList.remove('on'));b.classList.add('on');S.tab=b.dataset.tab;panel()});$$('[data-l]').forEach(b=>b.onchange=()=>{S.layers[b.dataset.l]=b.checked;draw2();build()});$('#menu').onclick=e=>{let b=e.target.closest('button');if(!b)return;let a=b.dataset.a;if(a==='new'){if(confirm('Criar novo projeto?')){S.shapes=[];S.profiles=[];S.sel=[];S.lsf=0;draw2();build();panel()}}else if(a==='export')csv();else if(a==='print')print();else if(a==='open'||a==='import')$('#file').click();else toast('Função preparada: '+b.textContent)};$('#file').onchange=e=>toast('Referência importada: '+(e.target.files[0]?.name||''));
function demo(){fix({kind:'rect',a:{x:260,y:300},b:{x:650,y:530},height:0,elev:0});S.sel=[S.shapes[0].id];panel()}resize();window.onresize=resize;panel();demo()})();
